### ISSUE TITLE
Doc build fails because of missing package

### ISSUE THREAD

**Issue by tonybaloney** [pybee/toga#101]
Whilst building the docs on RTD, you'll see in the logs:
```

/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/docs/reference/widgets/app.rst:6: WARNING: autodoc: failed to import class u'App' from module u'toga.interface.app'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/__init__.py", line 13, in <module>
    import toga.interface.app  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/__init__.py", line 6, in <module>
    from .widgets.box import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/widgets/box.py", line 1, in <module>
    from .base import Widget
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/widgets/base.py", line 1, in <module>
    from colosseum import CSSNode
ImportError: No module named colosseum
/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/docs/reference/widgets/box.rst:4: WARNING: autodoc: failed to import class u'Box' from module u'toga.interface.widgets.box'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/__init__.py", line 13, in <module>
    import toga.interface.app  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/__init__.py", line 6, in <module>
    from .widgets.box import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/widgets/box.py", line 1, in <module>
    from .base import Widget
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/widgets/base.py", line 1, in <module>
    from colosseum import CSSNode
```
This is because colosseum is not listed as a dependency in setup.py in the package root, but is in setup.py in the `core` package. 
RTD supports virtualenvs, which is enabled for this project but you need to tell it to install other packages if required.
Until this is fixed, none of the autodoc will work

@freakboy3742

**Comment by freakboy3742** [comment]
This is odd. There might be a need to do some refactoring here, because Colosseum *shouldn't* need to be a dependency. The fact that it is a dependency is almost certainly historical - but when you're using a backend like toga-web, CSS is native, so there isn't a need for a support library. There may be a need to separate out the parts of CSSNode that are describing the position of elements from the parts that actually do the layout.

**Comment by tonybaloney** [comment]
@freakboy3742 I can't see how it couldn't be a dependency. All of the widgets have `style` as an initializer argument, which expects a `CSSNode` and if not provided then will default to a new instance of `CSSNode`, which belongs to the colosseum package. Unless that behaviour is going to change?
https://github.com/pybee/toga/blob/master/src/core/toga/interface/widgets/base.py#L37

**Comment by freakboy3742** [comment]
Oh - there would definitely need to be some fairly major refactoring. The idea would be to separate the idea of a "node" object - which is just a description of a position and size of a box - and the style object, which lays out nodes. The node object can be a duck type or well defined interface; the style object then just needs an interface that can be applied.

**Comment by tonybaloney** [comment]
Why not just make '`style` a named tuple or model class and seperate the layout functionality out of the base widget. Apply style can still exists but it just applies properties. 
That way you're not mimicking the CSSNode behaviour, it becomes an implementation detail of colosseum and other renderers could use the same tuple/model

**Comment by tonybaloney** [comment]
Or attrs

**Comment by freakboy3742** [comment]
That about was what I was thinking - the `CSS` object is just a collection of literals, that can be applied to a node that knows where it is. That way "style" becomes completely independent of CSS, so if someone were to come up with a different layout scheme to CSS, they can use it - they just have to create a "style" object, and apply it to nodes in the layout tree.

**Comment by freakboy3742** [comment]
I've just pushed a refactor of Colosseum and the Cocoa backend of Toga that implements this refactor. I need to roll the equivalent changes through iOS and GTK, but the changes I've made so far should be enough to get the docs compiling (hopefully?)

**Comment by tonybaloney** [comment]
Should. RtD has a build output section, it's quite hidden but it does exist! 
Also, I've got a ton of docs added in another PR #102

**Comment by tonybaloney** [comment]
yey. different issue now 

```
/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/docs/reference/widgets/button.rst:33: WARNING: autodoc: failed to import class u'Button' from module u'toga.interface.widgets.button'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/__init__.py", line 10, in <module>
    import toga.interface.app  # NOQA
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/__init__.py", line 1, in <module>
    from .app import App
  File "/home/docs/checkouts/readthedocs.org/user_builds/toga/checkouts/latest/src/core/toga/interface/app.py", line 1, in <module>
    from builtins import id as identifier
ImportError: No module named builtins
```

**Comment by freakboy3742** [comment]
The Travertino refactor should have resolved this problem.
