### ISSUE TITLE
toga-demo trouble

### ISSUE THREAD

**Issue by CWinters19** [pybee/toga#135]
Hello,
I plan on using toga for a mobile app (iOS and Android, but the latter has higher priority). I just started learning python (3).
I run Xubuntu and do not use any virtual env but I did install the toga prerequisites prior to installing "toga" and "toga-demo" via pip3.
I had to use sudo here because the install would, similarly to installing "cryptography" last night via pip3, fail like this:

> Installing collected packages: colosseum, toga-core, toga-gtk, toga
Exception:
Traceback (most recent call last):
  File "/home/con/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/con/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/con/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/con/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/con/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/con/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/con/.local/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/con/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Keine Berechtigung: '/usr/local/lib/python3.5/dist-packages/colosseum

With sudo it installs fine though. But not the point.

When I try to run the toga-demo (I did not write any python with toga yet), it immediately fails.
On two very fresh installs of Xubuntu 16.04 and 16.10. What I get is this:

> con@con-pc:~$ toga-demo
(toga-demo:2090): GLib-GIO-CRITICAL **: g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/widgets/icon.py", line 20, in __impl
    return self._impl_cache[size]
KeyError: 32
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/app.py", line 139, in _startup
    self.startup()
  File "/usr/local/lib/python3.5/dist-packages/toga_demo/app.py", line 55, in startup
    self.main_window.toolbar = [cmd1, toga.SEPARATOR, cmd2]
  File "/usr/local/lib/python3.5/dist-packages/toga/interface/window.py", line 127, in toolbar
    self._set_toolbar(items)
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/window.py", line 42, in _set_toolbar
    item_impl.set_icon_widget(toolbar_item.icon._impl_32)
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/widgets/icon.py", line 28, in <lambda>
    _impl_32 = property(lambda self: self.__impl(32))
  File "/usr/local/lib/python3.5/dist-packages/toga_gtk/widgets/icon.py", line 23, in __impl
    GdkPixbuf.Pixbuf.new_from_file(self._filename).scale_simple(size, size, GdkPixbuf.InterpType.BILINEAR)
GLib.Error: g-file-error-quark: Failed to open file '/usr/local/lib/python3.5/dist-packages/resources/tiberius.icns': No such file or directory (4)

And sudo doesn't help me here, which was foreseeable since the demo is just running code, not installing it.
The problem shouldn't be Xubuntu, the only difference to Ubuntu is Xfce and that shouldn't brick toga, should it?
Is there something else toga needs to run besides the official prerequisites?
And how can I fix this? Like I said I am very new to this so I really can't move forward without your help.

Thank you!

**Comment by aramiscd** [comment]
Same problem here on Ubuntu 16.10.

    $ source env/bin/activate.fish
    (env) $ toga-demo
    (toga-demo:23714): GLib-GIO-CRITICAL **: g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed
    Traceback (most recent call last):
      File "/home/aramis/py-playground/env/lib/python3.5/site-packages/toga_gtk/widgets/icon.py", line 20, in __impl
        return self._impl_cache[size]
    KeyError: 32
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/aramis/py-playground/env/lib/python3.5/site-packages/toga_gtk/app.py", line 139, in _startup
        self.startup()
      File "/home/aramis/py-playground/env/lib/python3.5/site-packages/toga_demo/app.py", line 55, in startup
        self.main_window.toolbar = [cmd1, toga.SEPARATOR, cmd2]
      File "/home/aramis/py-playground/env/lib/python3.5/site-packages/toga/interface/window.py", line 127, in toolbar
        self._set_toolbar(items)
      File "/home/aramis/py-playground/env/lib/python3.5/site-packages/toga_gtk/window.py", line 42, in _set_toolbar
        item_impl.set_icon_widget(toolbar_item.icon._impl_32)
      File "/home/aramis/py-playground/env/lib/python3.5/site-packages/toga_gtk/widgets/icon.py", line 28, in <lambda>
        _impl_32 = property(lambda self: self.__impl(32))
      File "/home/aramis/py-playground/env/lib/python3.5/site-packages/toga_gtk/widgets/icon.py", line 23, in __impl
        GdkPixbuf.Pixbuf.new_from_file(self._filename).scale_simple(size, size, GdkPixbuf.InterpType.BILINEAR)
    GLib.Error: g-file-error-quark: Failed to open file '/home/aramis/py-playground/env/lib/python3.5/site-packages/resources/tiberius.icns': No such file or directory (4)

**Comment by freakboy3742** [comment]
I believe this problem has been addressed by pybee/toga#122 - if you install toga-demo from a github checkout and you still get this problem, please reopen this ticket.

**Comment by aramiscd** [comment]
Toga-demo from github works.  Thanks.
