### ISSUE TITLE
'module' object has no attribute 'OptionContainer'

### ISSUE THREAD

**Issue by retsyo** [pybee/toga#166]
I have installed via `pip install toga-demo` on my win64 bits with `Python 3.4.4 |Anaconda 2.3.0 (64-bit)`. But 
```bash
E:\prg\py\Anaconda3_64\Scripts>toga-demo.exe
Traceback (most recent call last):
  File "e:\prg\py\anaconda3_64\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\prg\py\anaconda3_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\prg\py\Anaconda3_64\Scripts\toga-demo.exe\__main__.py", line 9, in <m
odule>
  File "e:\prg\py\anaconda3_64\lib\site-packages\toga_demo\__main__.py", line 5,
 in run
    main().main_loop()
  File "e:\prg\py\anaconda3_64\lib\site-packages\toga_winforms\app.py", line 49,
 in main_loop
    self._startup()
  File "e:\prg\py\anaconda3_64\lib\site-packages\toga_winforms\app.py", line 41,
 in _startup
    self.startup()
  File "e:\prg\py\anaconda3_64\lib\site-packages\toga_demo\app.py", line 15, in
startup
    left_container = toga.OptionContainer()
AttributeError: 'module' object has no attribute 'OptionContainer'
```

**Comment by freakboy3742** [comment]
Toga demo doesn't work on windows (yet), due to a couple of missing widgets. See #115 and pybee/toga-demo#4

**Comment by RyanHope** [comment]
I saw this flag mentioned, but only in the context of OSX.
