### ISSUE TITLE
Toga-demo and Toga raises AttributeError

### ISSUE THREAD

**Issue by winza83** [pybee/toga#210]
Upon trying to run python -m helloworld after going through the tutorial in https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html, I am getting an Attribute error:

`(env) Winza-MB:pybee Winza$ python -m helloworld
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Winza/Documents/projects/pybee/helloworld.py", line 1, in <module>
    import toga
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga/__init__.py", line 114, in <module>
    set_platform()
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga/__init__.py", line 86, in set_platform
    local_vars['platform'] = importlib.import_module(module_name)
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga_cocoa/__init__.py", line 2, in <module>
    from .app import *
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga_cocoa/app.py", line 8, in <module>
    from .command import Command, Group
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga_cocoa/command.py", line 3, in <module>
    from .widgets.icon import Icon
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga_cocoa/widgets/icon.py", line 4, in <module>
    from ..libs import NSImage
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga_cocoa/libs/__init__.py", line 1, in <module>
    from .appkit import *
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/toga_cocoa/libs/appkit.py", line 5, in <module>
    from rubicon.objc import *
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/rubicon/objc/__init__.py", line 3, in <module>
    from .objc import (
  File "/Users/Winza/Documents/projects/pybee/env/lib/python3.6/site-packages/rubicon/objc/objc.py", line 343, in <module>
    objc.object_isClass.restype = c_bool
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fff6e2867d8, object_isClass): symbol not found`

Further info:  I'm using OSX 10.9, virtualenv version 15.0.1 and have python 3.6.

**Comment by freakboy3742** [comment]
This is an issue with macOS version support. The `object_isClass()` method was introduced in macOS 10.10.

The issue should be resolved if you update Rubicon; we corrected this problem by adding a workaround for macOS 10.8 and 10.9 about a month after you reported this issue.
