### ISSUE TITLE
AttributeError: 'VPaned' object has no attribute 'get_allcoation'

### ISSUE THREAD

**Issue by lukemaxwell** [pybee/toga#224]
Using a splitcontainer with horizontal direction raises an attribute error:

```
Traceback (most recent call last):
  File "/home/env/lib/python3.4/site-packages/toga_gtk/window.py", line 82, in _on_size_allocate
    height=allocation.height
  File "/home/env/lib/python3.4/site-packages/toga/interface/widgets/base.py", line 312, in _update_layout
    self._update_child_layout()
  File "/home/env/lib/python3.4/site-packages/toga_gtk/widgets/splitcontainer.py", line 60, in _update_child_layout
    size = self._impl.get_allcoation().height
AttributeError: 'VPaned' object has no attribute 'get_allcoation'
```
 Should be `get_allocation()` rather than `get_allcoation()`

**Comment by freakboy3742** [comment]
Fixed by #241
