### ISSUE TITLE
Tutorials 1, 2, and 3 are causing Attribute and Type Errors in Gtk+

### ISSUE THREAD

**Issue by danyeaw** [pybee/toga#314]
Tutorial1 and 3:

    Traceback (most recent call last):
        File "toga/src/gtk/toga_gtk/widgets/box.py", line 41, in do_size_allocate self.interface.refresh()
        File "toga/src/core/toga/widgets/base.py", line 126, in refresh super().refresh(self._impl.viewport)
    AttributeError: 'Box' object has no attribute 'viewport'

Tutorial2:
    
    Traceback (most recent call last):
        File "/toga/src/gtk/toga_gtk/app.py", line 140, in startup self.interface.startup()
        File "/toga/src/core/toga/app.py", line 142, in startup self.main_window.content = self._startup_method(self)
        File "/toga/examples/tutorial2/tutorial/app.py", line 62, in build split.content = [left_container, right_container]
        File "/toga/src/core/toga/widgets/splitcontainer.py", line 69, in content widget.refresh()
        File "/toga/src/core/toga/widgets/scrollcontainer.py", line 58, in refresh super().refresh()
        File "/toga/src/core/toga/widgets/base.py", line 127, in refresh self.refresh_sublayouts()
        File "/toga/src/core/toga/widgets/scrollcontainer.py", line 93, in refresh_sublayouts for widget in self._content:
    TypeError: 'Box' object is not iterable

Ubuntu 17.10

**Comment by freakboy3742** [comment]
Ok - I think I know the source of these. They're related to a late change I made to correct support for SplitContainer and OptionContainer. If you don't have any luck digging into this, I should get a chance to take a look in the next day or two.
