### ISSUE TITLE
[MacOs] TypeError: 'ObjCInstance' object is not callable (tutorial 0)

### ISSUE THREAD

**Issue by svandragt** [pybee/toga#322]
* I create a new directory
* pipenv install toga
* copy and paste the code from tutorial 0 (https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) into helloworld.py
* execute pipenv run python -m helloworld

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/Documents/src/tests/toga0.py", line 24, in <module>
    main().main_loop()
  File "~/.local/share/virtualenvs/tests-2BpcsSnM/lib/python3.6/site-packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "~/.local/share/virtualenvs/tests-2BpcsSnM/lib/python3.6/site-packages/toga_cocoa/app.py", line 95, in _startup
    self._impl = NSApplication.sharedApplication()
TypeError: 'ObjCInstance' object is not callable

```
Latest High Sierra, Python 3.6.4

**Comment by freakboy3742** [comment]
Thanks for the report.

Looks like you're hitting [a known problem with Toga on High Sierra](https://github.com/pybee/toga/issues/243); it's been fixed in the development branch.

If you want to try out the development branch, you can't just "pip install -e ." in the root of the directory; it's a little more complicated. You essentially need to set up a development environment, as described in [the contribution documentation](https://toga.readthedocs.io/en/latest/how-to/contribute.html#set-up-your-development-environment)

Sorry for the inconvenience this causes; we're hoping to push out a new version of Toga very soon.
