### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_impl'

### ISSUE THREAD

**Issue by AlphaRoy14** [pybee/toga#356]
## Expected Behavior
Should show a window and button as in [tutorial 0](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html)

## Current Behavior

Shows the following error
```
Traceback (most recent call last):
  File "app1.py", line 24, in <module>
    main().main_loop()
  File "/Users/roy/Desktop/temp/toga/src/core/toga/app.py", line 167, in main_loop
    self._impl.main_loop()
  File "/Users/roy/Desktop/temp/toga/src/cocoa/toga_cocoa/app.py", line 163, in main_loop
    self.create()
  File "/Users/roy/Desktop/temp/toga/src/cocoa/toga_cocoa/app.py", line 112, in create
    self.interface.startup()
  File "/Users/roy/Desktop/temp/toga/src/core/toga/app.py", line 156, in startup
    self.main_window.content = self._startup_method(self)
  File "app1.py", line 9, in build
    box = toga.Box()
  File "/Users/roy/Desktop/temp/toga/src/core/toga/widgets/box.py", line 23, in __init__
    self._impl = self.factory.Box(interface=self)
  File "/Users/roy/Desktop/temp/toga/src/cocoa/toga_cocoa/widgets/base.py", line 13, in __init__
    self.interface.style.reapply()
  File "/Users/roy/Desktop/temp/venv/lib/python3.6/site-packages/travertino/declaration.py", line 88, in reapply
    self.apply(style, getattr(self, style))
  File "/Users/roy/Desktop/temp/toga/src/core/toga/style/pack.py", line 91, in apply
    self._applicator.set_hidden(hidden)
  File "/Users/roy/Desktop/temp/toga/src/core/toga/style/applicator.py", line 21, in set_hidden
    self.widget._impl.set_hidden(hidden)
  File "/Users/roy/Desktop/temp/toga/src/cocoa/toga_cocoa/widgets/base.py", line 51, in set_hidden
    for view in self._container._impl.subviews:
AttributeError: 'NoneType' object has no attribute '_impl'
```
## Steps to reproduce

1. ` pip3 install -e src/core`

2. ` pip3 install -e src/dummy`

3.` pip3 install -e src/cocoa`

## Your Environment

running in virtual environment of macOS High Sierra version 10.13.1

* Python Version (list the specific version number)
Python 3.6.3

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ X] OSX
  - [ ] Linux
  - [ ] Windows
  - [ ] Ubuntu

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ X] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
@AlphaRoy14 Thanks for the report. Unfortunately, I haven't been able to reproduce the behavior you report. Can you confirm:

* The tutorial code you're running - did you copy and paste or retype? (Just trying to eliminate a typo in the input as the source of the problem)
* The git revision of the toga repository that you've installed.
* Whether you're running in a virtual environment (and if so, how you created it)
* The contents of `pip freeze`

**Comment by AlphaRoy14** [comment]
@freakboy3742  

- The code was copy pasted 

-` $ git show` outputs this `commit 9e887767f53d19ed45932678433c17c047f5e08e (HEAD -> master, origin/master, origin/HEAD)`

- yes virtual environment is running. 
```
$ python3 -m venv venv
$ source venv/bin/activate
```

- `$ pip3 freeze` shows this 
```
colosseum==0.1.6
coverage==4.5
cssutils==1.0.2
ll-xist==5.31
pycoco==0.7.2
pyobjc==4.1
pyobjc-core==4.1
pyobjc-framework-Accounts==4.1
pyobjc-framework-AddressBook==4.1
pyobjc-framework-AppleScriptKit==4.1
pyobjc-framework-AppleScriptObjC==4.1
pyobjc-framework-ApplicationServices==4.1
pyobjc-framework-Automator==4.1
pyobjc-framework-AVFoundation==4.1
pyobjc-framework-AVKit==4.1
pyobjc-framework-CalendarStore==4.1
pyobjc-framework-CFNetwork==4.1
pyobjc-framework-CloudKit==4.1
pyobjc-framework-Cocoa==4.1
pyobjc-framework-Collaboration==4.1
pyobjc-framework-ColorSync==4.1
pyobjc-framework-Contacts==4.1
pyobjc-framework-ContactsUI==4.1
pyobjc-framework-CoreBluetooth==4.1
pyobjc-framework-CoreData==4.1
pyobjc-framework-CoreLocation==4.1
pyobjc-framework-CoreML==4.1
pyobjc-framework-CoreServices==4.1
pyobjc-framework-CoreSpotlight==4.1
pyobjc-framework-CoreText==4.1
pyobjc-framework-CoreWLAN==4.1
pyobjc-framework-CryptoTokenKit==4.1
pyobjc-framework-DictionaryServices==4.1
pyobjc-framework-DiskArbitration==4.1
pyobjc-framework-EventKit==4.1
pyobjc-framework-ExceptionHandling==4.1
pyobjc-framework-ExternalAccessory==4.1
pyobjc-framework-FinderSync==4.1
pyobjc-framework-FSEvents==4.1
pyobjc-framework-GameCenter==4.1
pyobjc-framework-GameController==4.1
pyobjc-framework-GameKit==4.1
pyobjc-framework-GameplayKit==4.1
pyobjc-framework-ImageCaptureCore==4.1
pyobjc-framework-IMServicePlugIn==4.1
pyobjc-framework-InputMethodKit==4.1
pyobjc-framework-InstallerPlugins==4.1
pyobjc-framework-InstantMessage==4.1
pyobjc-framework-Intents==4.1
pyobjc-framework-IOSurface==4.1
pyobjc-framework-iTunesLibrary==4.1
pyobjc-framework-LatentSemanticMapping==4.1
pyobjc-framework-LaunchServices==4.1
pyobjc-framework-libdispatch==4.1
pyobjc-framework-LocalAuthentication==4.1
pyobjc-framework-MapKit==4.1
pyobjc-framework-MediaAccessibility==4.1
pyobjc-framework-MediaLibrary==4.1
pyobjc-framework-MediaPlayer==4.1
pyobjc-framework-ModelIO==4.1
pyobjc-framework-MultipeerConnectivity==4.1
pyobjc-framework-NetFS==4.1
pyobjc-framework-NetworkExtension==4.1
pyobjc-framework-NotificationCenter==4.1
pyobjc-framework-OpenDirectory==4.1
pyobjc-framework-Photos==4.1
pyobjc-framework-PhotosUI==4.1
pyobjc-framework-PreferencePanes==4.1
pyobjc-framework-PubSub==4.1
pyobjc-framework-QTKit==4.1
pyobjc-framework-Quartz==4.1
pyobjc-framework-SafariServices==4.1
pyobjc-framework-SceneKit==4.1
pyobjc-framework-ScreenSaver==4.1
pyobjc-framework-ScriptingBridge==4.1
pyobjc-framework-SearchKit==4.1
pyobjc-framework-Security==4.1
pyobjc-framework-SecurityFoundation==4.1
pyobjc-framework-SecurityInterface==4.1
pyobjc-framework-ServiceManagement==4.1
pyobjc-framework-Social==4.1
pyobjc-framework-SpriteKit==4.1
pyobjc-framework-StoreKit==4.1
pyobjc-framework-SyncServices==4.1
pyobjc-framework-SystemConfiguration==4.1
pyobjc-framework-Vision==4.1
pyobjc-framework-WebKit==4.1
rubicon-objc==0.2.10
toga==0.2.15
-e git+https://github.com/AlphaRoy14/toga.git@9e887767f53d19ed45932678433c17c047f5e08e#egg=toga_cocoa&subdirectory=src/cocoa
-e git+https://github.com/AlphaRoy14/toga.git@9e887767f53d19ed45932678433c17c047f5e08e#egg=toga_core&subdirectory=src/core
toga-demo==0.2.15
-e git+https://github.com/AlphaRoy14/toga.git@9e887767f53d19ed45932678433c17c047f5e08e#egg=toga_dummy&subdirectory=src/dummy
travertino==0.1.2
```

**Comment by AlphaRoy14** [comment]
For an error unknown toga wasn't working on the initial virtual environment. However it seems to work fine when I made a new virtual environment and followed the installation instructions. Sorry for the inconvenience caused.

**Comment by freakboy3742** [comment]
@AlphaRoy14 Thanks for those details. From the look if it, the problem is a clash with other pieces in the system - you've got 0.2.15 series toga, 0.3.0.dev series toga, and PyObjC all in the same environment. I'm not 100% sure how that manifests with the problems you're seeing, but if moving to a clean virtual environment fixes things, all the better.
