### ISSUE TITLE
Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

### ISSUE THREAD

**Issue by hobarrera** [pybee/toga#38]
Trying to run the demo, I get an error.

```
$ toga-demo
Traceback (most recent call last):
  File "/home/hugo/tmp/env/bin/toga-demo", line 7, in <module>
    from toga_demo.__main__ import main
  File "/home/hugo/tmp/env/lib/python3.4/site-packages/toga_demo/__main__.py", line 7, in <module>
    import toga
  File "/home/hugo/tmp/env/lib/python3.4/site-packages/toga/__init__.py", line 78, in <module>
    set_platform()
  File "/home/hugo/tmp/env/lib/python3.4/site-packages/toga/__init__.py", line 64, in set_platform
    locals['platform'] = importlib.import_module(module_name)
  File "/home/hugo/tmp/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/hugo/tmp/env/lib/python3.4/site-packages/toga_gtk/__init__.py", line 21, in <module>
    from .widgets.webview import *
  File "/home/hugo/tmp/env/lib/python3.4/site-packages/toga_gtk/widgets/webview.py", line 9, in <module>
    from gi.repository import WebKit
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/gi/importer.py", line 68, in load_module
    dynamic_module._load()
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 294, in _load
    self._introspection_module = get_introspection_module(self._namespace)
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 273, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 122, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded
```

Details:
```
$ uname -a
Linux athena.barrera.io 3.16.2-1-ARCH #1 SMP PREEMPT Sat Sep 6 13:12:51 CEST 2014 x86_64 GNU/Linux
$ python --version
Python 3.4.1
```

I'm not sure what else might be relevant.

**Comment by freakboy3742** [comment]
Closing this on the basis that the mechanism for importing gi has changed in a way that *should* address this problem; if you still experience problems, please let us know.
