### ISSUE TITLE
Missing icon resources for tutorial 2

### ISSUE THREAD

**Issue by 00willo** [pybee/toga#47]
On running the tutorial, I get the following:

```
Traceback (most recent call last):
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/app.py", line 84, in _startup
    self.startup()
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/app.py", line 90, in startup
    self.main_window.content = self._startup_method(self)
  File "first-app.py", line 71, in build
    toga.EXPANDING_SPACER, cmd4]
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/window.py", line 60, in toolbar
    item_impl.set_icon_widget(toolbar_item.icon._impl_32)
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/widgets/icon.py", line 35, in <lambda>
    _impl_32 = property(lambda self: self.__impl(32))
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/widgets/icon.py", line 30, in __impl
    GdkPixbuf.Pixbuf.new_from_file(self._filename).scale_simple(size, size, GdkPixbuf.InterpType.BILINEAR)
GLib.Error: g-file-error-quark: Failed to open file 'icons/brutus.icns': No such file or directory (4)
```

Looking through closed issues, I found #13 and #21, but they're mainly about things missing from the toga_demo and also reference brutus.icns.

After I copied the brutus.png file across and patched my python file to

```
cmd1 = toga.Command(action1, 'Action 1', tooltip='Perform action 1', icon='icons/brutus.png') 
```

I end up with:

```
Traceback (most recent call last):
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/app.py", line 84, in _startup
    self.startup()
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/app.py", line 90, in startup
    self.main_window.content = self._startup_method(self)
  File "first-app.py", line 71, in build
    toga.EXPANDING_SPACER, cmd4]
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/window.py", line 60, in toolbar
    item_impl.set_icon_widget(toolbar_item.icon._impl_32)
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/widgets/icon.py", line 35, in <lambda>
    _impl_32 = property(lambda self: self.__impl(32))
  File "/home/willo/.virtualenvs/toga/lib/python2.7/site-packages/toga_gtk/widgets/icon.py", line 30, in __impl
    GdkPixbuf.Pixbuf.new_from_file(self._filename).scale_simple(size, size, GdkPixbuf.InterpType.BILINEAR)
GLib.Error: gdk-pixbuf-error-quark: Couldn't recognise the image file format for file 'icons/brutus.icns' (3)
```

So, it must be an actual icon file, which is missing.

The tiberious icon is supplied in the toga/toga/resources/ directory included in this repo and is reference by TIBERIUS_ICON in toga_gtk/widgets/icon.py included in the https://github.com/pybee/toga-gtk

**Comment by 00willo** [comment]
Maybe I'd suggest including the resource in this repo, patching the icon.py in toga-gtk to include something like:

    BRUTUS_ICON = Icon('brutus.icns', system=True) 

Then patch the tutorial example to reference toga.BRUTUS_ICON

**Comment by Olbiv** [comment]
I have the same problem on Xubuntu Linux. 
If i set all the icons to `icon=toga.TIBERIUS_ICON` then the program will run, but strangely only "Action4" displays an icon.

**Comment by lubegamark** [comment]
This only worked when I created an icons folder and manually added the icons and referenced them.
```        cmd4 = toga.Command(
            action4, 'Action 4',
            tooltip='Perform action 4',
            icon='icons/brutus-32.png'
        )
```

**Comment by danyeaw** [comment]
Tutorial 2 has a link after the source code to the icons: [https://toga.readthedocs.io/en/latest/_downloads/icons.zip](url)
Extract them to the location where you are trying to run the tutorial from, and they should go in to an icons folder. This should work with the exact code from the tutorial.

It also looks like you aren't using python3 which is required for Toga since your error messages reference 2.7.
> .virtualenvs/toga/lib/python2.7/

@00willo can you try this and verify that this is still an issue?
