### ISSUE TITLE
ImageView Example crash Windows

### ISSUE THREAD

**Issue by ibigpapa** [pybee/toga#501]
## Expected Behavior

The image view example to render

## Current Behavior

Crashes before loading anything

```
python.exe -m imageview

Unhandled Exception: Python.Runtime.PythonException: FileNotFoundException : resources/brutus.png
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromFile(String filename)
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
## Steps to reproduce

1. launch imageview example

## Your Environment

* Python Version (list the specific version number) 3.6.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [ x ] Windows - version: Win10 1607
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ x ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by obulat** [comment]
This issue is caused by the placement of resources folder. If the resources folder is in the top-most directory, the app works fine. Is this the correct placement?
**imageview**
- imageview (  __init__.py, __main__.py, app.py)
- resources ( brutus.png )
- ( README.rst, setup.py )

Also, raising an error if the image file is not found, instead of crashing the app, seems a better solution.

**Comment by obulat** [comment]
#521 solved this issue, it can now be closed.

**Comment by freakboy3742** [comment]
@bobm123 There *shouldn't* be any variation between platforms, but it's possible some variation has crept in; and yes, it should be an error, rather than a hard crash.
