### ISSUE TITLE
Error looking for icon for tutorial for 0.3.0.dev9

### ISSUE THREAD

**Issue by brettcannon** [pybee/toga#567]
This is with Python 3.6.5 in a clean venv:
```
(.venv) PS C:\Users\_\Desktop\toga_tutorial> python .\helloworld.py
[Winforms] No valid icon format available for C:\Users\brcan\Desktop\toga_tutorial\.venv\lib\site-packages\toga\resources\tiberius; fall back on Tiberius instead

Unhandled Exception: Python.Runtime.PythonException: FileNotFoundException : Could not find file 'C:\Users\brcan\Desktop\toga_tutorial\.venv\lib\site-packages\toga\resources\tiberius.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by freakboy3742** [comment]
Hrm... which tutorial is this (i.e., tutorial 0? tutorial 1?)

On a related note - if you've got any tips/pointers on how to run automated tests of GUI code on Windows, I'd love to hear about them - at the moment, we're only doing automated testing of internal APIs, so calls on GUI functionality are *far* too succeptible to breakage.

**Comment by brettcannon** [comment]
@freakboy3742 I know as much about Windows GUI programming as Toga has taught me so far. 😁 @d3r3kk might know.

**Comment by brettcannon** [comment]
And this was tutorial 0; basically you can't load an app on Windows without that file in place.

**Comment by d3r3kk** [comment]
I am just now learning how to get up and running with toga, on a Windows machine (also on Linux). If I can, I will have a look and see if I can help out with automated tests and all that. 

Not to bum anyone out, but pretty much all my prior experience with GUI tests is a storied tale of sorrow and loss...

But hey!

**Comment by freakboy3742** [comment]
@d3r3kk Any assistance (or even guidance) you can provide would be most welcome.

And yeah... I've already got the scars from past battles with GUI testing. Nice to know time hasn't improved the situation... :sigh:...
