### ISSUE TITLE
Python.Runtime.PythonException: Exception : Window is already associated with an App

### ISSUE THREAD

**Issue by diyseguy** [pybee/toga#587]
## Expected Behavior

Following along with the video intro for Freedom app, running 'python -m freedom' inside the freedom directory should launch the app

## Current Behavior

running 'python -m freedom' inside the freedom directory produces this error:

python -m freedom

Unhandled Exception: Python.Runtime.PythonException: Exception : Window is already associated with an App
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
(venv) 

## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)
Python 3.6.5
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)
Windows 10

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x ] Windows - version: 10
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [x ] android
  - [x ] cocoa
  - [x ] django 
  - [x ] gtk
  - [x ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [x ] win32
  - [ ] Other (please specify)

**Comment by diyseguy** [comment]
I was able to get past this by re-initializing the demo for only one platform

**Comment by stantonxu** [comment]
@diyseguy , could you please give a bit detail how you re-initialize it and work around? I met the same problem even for "toga-demo".

**Comment by stantonxu** [comment]
Just figured out, it works for Python 3.6 but not 3.7.

**Comment by alperengormez** [comment]
I am facing the same issue even though I am running Python 3.6. 
I run the following command: `python -m alperend `
And it gives the following output:

```
WARNING: Can't find icon resources/alperend; falling back to default icon
Traceback (most recent call last):
  File "C:\Users\Alperen\Anaconda3\envs\appicin\lib\site-packages\toga_winforms\app.py", line 128, in run_app
    self.create()
  File "C:\Users\Alperen\Anaconda3\envs\appicin\lib\site-packages\toga_winforms\app.py", line 64, in create
    self.interface.startup()
  File "D:\alperend\alperend\app.py", line 27, in startup
    self.main_window.app = self
  File "C:\Users\Alperen\Anaconda3\envs\appicin\lib\site-packages\toga\window.py", line 79, in app
    raise Exception("Window is already associated with an App")
Exception: Window is already associated with an App
```

Is there a workaround for this problem?

**Comment by AkashVShendage** [comment]
```
Traceback (most recent call last):
  File "f:\python\beeware\bwenv\lib\site-packages\toga_winforms\app.py", line 184, in run_app
    self.create()
  File "f:\python\beeware\bwenv\lib\site-packages\toga_winforms\app.py", line 81, in create
    self.interface.startup()
  File "f:\python\beeware\bwenv\lib\site-packages\toga_demo\app.py", line 13, in startup
    self.main_window.app = self
  File "f:\python\beeware\bwenv\lib\site-packages\toga\window.py", line 79, in app
    raise Exception("Window is already associated with an App")
Exception: Window is already associated with an App

```
Try this commands...

```
pip install --pre toga-demo
toga-demo
```
