### ISSUE TITLE
ImageView Example Broken

### ISSUE THREAD

**Issue by danieloconell** [pybee/toga#606]
## Expected Behavior
When running the ImageView example expected to see a Bee and a Bull appear.

## Current Behavior
A ValueError is being raised saying that the image "brutus.png" is unavailable.  See errors below for more.
```
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.7/site-packages/toga_gtk/app.py", line 71, in startup
    self.interface.startup()
  File "/home/daniel/git/toga/examples/imageview/imageview/app.py", line 18, in startup
    imageview_from_path = toga.ImageView(image_from_path)
  File "/home/daniel/.local/lib/python3.7/site-packages/toga/widgets/imageview.py", line 23, in __init__
    self.image = image
  File "/home/daniel/.local/lib/python3.7/site-packages/toga/widgets/imageview.py", line 33, in image
    self._impl.set_image(self._image)
  File "/home/daniel/.local/lib/python3.7/site-packages/toga_gtk/widgets/imageview.py", line 35, in set_image
    raise ValueError("No image file available at ", full_image_path)
ValueError: ('No image file available at ', '/home/daniel/git/toga/examples/imageview/imageview/resources/brutus.png')
```

## Steps to reproduce
1. Go to the examples/imageview directory.
2. Run python3 -m imageview

## Your Environment
* Python Version 3.7.0
* Operating System and Version
  - Linux - Manjaro:  - 17.1.12:
  - Toga - 0.3.0.dev10

**Comment by danyeaw** [comment]
Closed by #645
