### ISSUE TITLE
Issues running the basic app on openSuse Tumbleweed

### ISSUE THREAD

**Issue by MisterY** [pybee/toga#621]
Hi, any assistance would be great! I'm unable to figure out what the problem is nor to debug using VS Code.

## Expected Behavior

I would like to run the most basic Toga app and see a demo of the technology.

## Current Behavior

Trying the very first app from the Toga tutorial and getting the following error:

```
(venv) alen@andromede:~/src/python-gui/bee-toga> python -m hello
Traceback (most recent call last):
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga_gtk/app.py", line 7, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alen/src/python-gui/bee-toga/hello.py", line 25, in <module>
    app = main()
  File "/home/alen/src/python-gui/bee-toga/hello.py", line 22, in main
    return toga.App('First App', 'org.pybee.helloworld', startup=build)
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga/app.py", line 53, in __init__
    self.factory = get_platform_factory(factory)
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga/platform.py", line 39, in get_platform_factory
    from toga_gtk import factory
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga_gtk/__init__.py", line 2, in <module>
    from .app import *
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga_gtk/app.py", line 65, in <module>
    raise RuntimeError("Unable to locate the Python GTK+ bindings. Have you run '%s'?" % installer_command)
RuntimeError: Unable to locate the Python GTK+ bindings. Have you run 'pacman -S python-gobject'?
```

When trying to run from vscode and adding a breakpoint in the listed app.py, I'm getting

![image](https://user-images.githubusercontent.com/462445/47618156-f8ad6a00-dacf-11e8-9057-331329fba996.png)

## Steps to reproduce

I've followed the instructions and created the virtualenv, installed all the dependencies, and ran the hello world module with "python -m". 

PyGObject is installed, I believe, as an RPM package and is accessible from Python code. I've successfully used it for WebView, for example.

## Your Environment

* Python Version 3.6.5

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [x] Linux - distro: openSuse   - version: Tumbleweed (current)
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [x] android
  - [ ] cocoa
  - [ ] django 
  - [x] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms 
  - [x] win32
  - [ ] Other (please specify)

**Comment by MisterY** [comment]
From what I can see, the toga_gtk/app.py finds the Python packages on my system in `/usr/lib/python3.6/dist-packages/` and it branches off to

```
elif os.path.isdir('/usr/lib/python%s/site-packages/' % (py_version,)):
    gi_system_install_path = '/usr/lib/python%s/site-packages/gi' % (py_version,)
```

but the gi path is incorrect, unfortunately.

**Comment by MisterY** [comment]
There is a way to add gi to virtual environment, fortunately:

https://stackoverflow.com/questions/39214803/how-to-install-python-gi-module-in-virtual-environment#43817335

```
pip install vext
pip install vext.gi
```

With that out of the way, running the hello world module gives:

```
(venv) alen@andromede:~/src/python-gui/bee-toga> python -m hello
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alen/src/python-gui/bee-toga/hello.py", line 25, in <module>
    app = main()
  File "/home/alen/src/python-gui/bee-toga/hello.py", line 22, in main
    return toga.App('First App', 'org.pybee.helloworld', startup=build)
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga/app.py", line 53, in __init__
    self.factory = get_platform_factory(factory)
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga/platform.py", line 39, in get_platform_factory
    from toga_gtk import factory
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga_gtk/__init__.py", line 2, in <module>
    from .app import *
  File "/home/alen/src/python-gui/bee-toga/venv/lib64/python3.6/site-packages/toga_gtk/app.py", line 71, in <module>
    from toga.interface.app import App as AppInterface
ModuleNotFoundError: No module named 'toga.interface'
```

**Comment by MisterY** [comment]
According to the [docs](https://toga.readthedocs.io/en/latest/background/architecture.html), interface is part of toga-core. That points to a funny thing:

![image](https://user-images.githubusercontent.com/462445/47618381-b5082f80-dad2-11e8-8d1a-a87a42798c0f.png)

**Comment by MisterY** [comment]
Following this [tip](https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip), I've installed toga-core 0.2.15 explicitly => `pip install 'toga-core==0.2.15'`.

And (yes! holy smokes!) I've got the basic app working!

I've added the steps as I was troubleshooting. Hopefully this would be useful for others, as well.
