### ISSUE TITLE
Not able to create and run the tutorial on linux

### ISSUE THREAD

**Issue by ItsBlinkHere** [pybee/toga#628]
## Expected Behavior
Should be able to create and run the tutorial on linux Ubuntu 18.04

## Current Behavior
When I run my setup.py file I get a `Failed building wheel for pygobject` error. Not sure if something is up with GTK. I have reproduced this on various different versions of linux. I though it might be something wrong with the python virtual environment so is tried various ways on creating then venv (virtualenv, using conda, the regular pythonic way) I also tried installing and running it without a venv and that didn't work either. Currently I am very confused.

## Steps to reproduce
1. Installed the GTK and WebKit
```sudo apt-get install python3-dev python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
[sudo] password for itsblinkhere:           
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-gtk-3.0 is already the newest version (3.22.30-1ubuntu1).
libcairo2-dev is already the newest version (1.15.10-2).
libgirepository1.0-dev is already the newest version (1.56.1-1).
python3-gi is already the newest version (3.26.1-2).
python3-gi-cairo is already the newest version (3.26.1-2).
python3-dev is already the newest version (3.6.5-3ubuntu1).
The following packages were automatically installed and are no longer required:
  libssl-doc linux-headers-4.15.0-36 linux-headers-4.15.0-36-generic linux-image-4.15.0-36-generic linux-modules-4.15.0-36-generic linux-modules-extra-4.15.0-36-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

2. Create and virtual env using any of the methods gives me the same results.
`virtualenv venv --python=python3.5`
`source venv/bin/activate`
`pip install cookiecutter briefcase`
`cookiecutter https://github.com/pybee/briefcase-template`
`cd helloworld/`
`python setup.py linux -s`

3. Here is the log
``` * Writing application template...
Template Python-Linux-template succesfully updated.
Project template: /home/itsblinkhere/.cookiecutters/Python-Linux-template
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-gtk==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/58/03/fd1b50d3e694191119e828e1455309e265cb80a17ea3a1f39eb0b411dc26/toga_gtk-0.3.0.dev11-py3-none-any.whl
Collecting gbulb>=0.5.3 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/92/cb/d2a0e4899cde5aa797e31d77a0a7422dcd188d880bb38d0e9d1b1196e5c6/gbulb-0.6.1.tar.gz
Collecting toga-core==0.3.0.dev11 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting pycairo>=1.17.0 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/a6/54/23d6cf3e8d8f1eb30e0e58f171b6f62b2ea75c024935492373639a1a08e4/pycairo-1.18.0.tar.gz
Collecting pygobject>=3.14.0 (from toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/8c/c8/f832d3b9cfda124e0f0f172e8ba07e2e4e8128354193cc08d54cfbc1cd94/PyGObject-3.30.2.tar.gz
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-gtk==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Building wheels for collected packages: gbulb, pycairo, pygobject
  Running setup.py bdist_wheel for gbulb ... done
  Stored in directory: /home/itsblinkhere/.cache/pip/wheels/92/57/1e/d484f762cdd6b5a1e737517f4e2d122ba261544a7e615f2269
  Running setup.py bdist_wheel for pycairo ... done
  Stored in directory: /home/itsblinkhere/.cache/pip/wheels/e6/bb/aa/7b71758ea95e5ae6f1aef55bbc34cc4dd236383dc6554af0c5
  Running setup.py bdist_wheel for pygobject ... error
  Complete output from command /home/itsblinkhere/Documents/new_env/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mriaw0yv/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-g8w_4moi --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.5/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.5/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.5/pygtkcompat
  creating build/lib.linux-x86_64-3.5/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/types.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/module.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_option.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_error.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/importer.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/_compat.py -> build/lib.linux-x86_64-3.5/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.5/gi
  creating build/lib.linux-x86_64-3.5/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.5/gi/repository
  creating build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.5/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.5/gi/overrides
  running build_ext
  pycairo: new API
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1241, in <module>
      main()
    File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1236, in main
      zip_safe=False,
    File "/home/itsblinkhere/Documents/new_env/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/itsblinkhere/Documents/new_env/venv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1076, in run
      self._setup_extensions()
    File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1071, in _setup_extensions
      add_pycairo(gi_cairo_ext)
    File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1055, in add_pycairo
      ext.include_dirs += [get_pycairo_include_dir()]
    File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 877, in get_pycairo_include_dir
      include_dir = find_path(find_new_api())
    File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 822, in find_new_api
      import cairo
  ImportError: No module named 'cairo'
  
  ----------------------------------------
  Failed building wheel for pygobject
  Running setup.py clean for pygobject
Successfully built gbulb pycairo
Failed to build pygobject
Installing collected packages: gbulb, travertino, toga-core, pycairo, pygobject, toga-gtk
  Running setup.py install for pygobject ... error
    Complete output from command /home/itsblinkhere/Documents/new_env/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mriaw0yv/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_jhh3dcp/install-record.txt --single-version-externally-managed --compile --install-headers /home/itsblinkhere/Documents/new_env/venv/include/site/python3.5/pygobject --home=/tmp/pip-target-at7csryi:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pygtkcompat
    copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.5/pygtkcompat
    copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.5/pygtkcompat
    copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.5/pygtkcompat
    creating build/lib.linux-x86_64-3.5/gi
    copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/types.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/docstring.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/module.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_constants.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_option.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_error.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/importer.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/__init__.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/_compat.py -> build/lib.linux-x86_64-3.5/gi
    copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.5/gi
    creating build/lib.linux-x86_64-3.5/gi/repository
    copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.5/gi/repository
    creating build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.5/gi/overrides
    copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.5/gi/overrides
    running build_ext
    pycairo: new API
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1241, in <module>
        main()
      File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1236, in main
        zip_safe=False,
      File "/home/itsblinkhere/Documents/new_env/venv/lib/python3.5/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/itsblinkhere/Documents/new_env/venv/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1076, in run
        self._setup_extensions()
      File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1071, in _setup_extensions
        add_pycairo(gi_cairo_ext)
      File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 1055, in add_pycairo
        ext.include_dirs += [get_pycairo_include_dir()]
      File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 877, in get_pycairo_include_dir
        include_dir = find_path(find_new_api())
      File "/tmp/pip-install-mriaw0yv/pygobject/setup.py", line 822, in find_new_api
        import cairo
    ImportError: No module named 'cairo'
    
    ----------------------------------------
Command "/home/itsblinkhere/Documents/new_env/venv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mriaw0yv/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_jhh3dcp/install-record.txt --single-version-externally-managed --compile --install-headers /home/itsblinkhere/Documents/new_env/venv/include/site/python3.5/pygobject --home=/tmp/pip-target-at7csryi" failed with error code 1 in /tmp/pip-install-mriaw0yv/pygobject/
 * Installing project code...
Processing /home/itsblinkhere/Documents/new_env/helloworld
Building wheels for collected packages: helloworld
  Running setup.py bdist_wheel for helloworld ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-259rct_c/wheels/b2/b8/84/a10e1942f46d7bdc5a0354815da5331cefa417af586c362132
Successfully built helloworld
Installing collected packages: helloworld
Successfully installed helloworld-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting Hello World
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/itsblinkhere/Documents/new_env/helloworld/linux/app/helloworld/__main__.py", line 1, in <module>
    from helloworld.app import main
  File "/home/itsblinkhere/Documents/new_env/helloworld/linux/app/helloworld/app.py", line 2, in <module>
    import toga
ImportError: No module named 'toga'

App started.
```

## Your Environment
* Python Version 3.5

* Operating System and Version 

  - [ ] macOS - version: 
  - [x] Linux - distro:   - 18.04:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

```lsb_release -a -u
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

* Toga Target

  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [x] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the report. We recently switched to pygobject as a way of accessing the system GTK libraries from within a virtual environment, so it's possible we're missing something in our installation instructions. The fact that you're getting errors about "no module named Cairo" is the first sign of this.

Can you confirm if you're able to run a basic "raw GTK" demo (e.g., [the Python GTK hello world](https://python-gtk-3-tutorial.readthedocs.io/en/latest/introduction.html) ) from within the same virtual environment where you're using briefcase? Toga is ultimately just a wrapper around those libraries, so if the base GTK stuff isn't working Toga won't work either.

Historically, when we've seen problems like this, it's been due to a system-level package not being installed - unfortunately, the debugging information that `pip install pygobject` provides isn't especially helpful.

**Comment by ItsBlinkHere** [comment]
So ive managed to reproduce this in most versions of python3. Only in python 3.6 does it partially work. I'm still getting GTK related errors though. 
```
Installation complete.
Starting Hello World
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Widget.set_hidden()
[GTK+] Not implemented: Button.set_background_color()
[GTK+] Not implemented: Widget.set_hidden()
```
I also just ran some of the examples here [https://github.com/sebp/PyGObject-Tutorial/tree/master/examples](url) and I did not get any of the same `[GTK+] Not implemented: errors` All the examples from PyGobject I tested ran without problems.

**Comment by freakboy3742** [comment]
Ok, so those aren't errors. They're warnings, notifying you about features that the GTK backend doesn't yet implement. If you're seeing those messages, you may not be seeing the "ideal" behavior, but the code still runs.

So, for example, if your code specifies a font for a text input, you wont see that font rendered; but the code will still *work* and allow you to see the widget.

We've done this because we've got multiple backends that we're trying to keep in sync, and if a feature isn't 100% critical to operation, it's easier to report limitations rather than crashing.

So - to be clear: Are you reporting a *crash* when you run an app, or just these warnings? Your original report says "unable to run the tutorial" - is it running but you're getting these warnings, or are you unable to run the app at all?

**Comment by ItsBlinkHere** [comment]
@freakboy3742  The error still happens for me on python3.5 and 3.7. But 3.6 works fine for some reason. Since I have a working solution I will close this report.
