### ISSUE TITLE
Microsoft Windows support?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [pybee/toga#69]
Is Windows 7 and above supported? (What are the prerequisites then?)

When I run `pip install toga-demo` I get an error:

```
[BEEWARE] λ pip install toga-demo
Collecting toga-demo
  Downloading toga_demo-0.2.2-py3-none-any.whl
Collecting toga>=0.2.2 (from toga-demo)
  Downloading toga-0.2.2-py3-none-any.whl
Collecting toga-win32; sys_platform == "win32" (from toga>=0.2.2->toga-demo)
  Downloading toga_win32-0.1.2-py2.py3-none-any.whl (54kB)
    100% |################################| 61kB 2.4MB/s
Collecting toga-cassowary (from toga-win32; sys_platform == "win32"->toga>=0.2.2->toga-demo)
  Downloading toga_cassowary-0.1.2-py2.py3-none-any.whl
Collecting cassowary (from toga-cassowary->toga-win32; sys_platform == "win32"->toga>=0.2.2->toga-demo)
  Downloading cassowary-0.5.1-py2.py3-none-any.whl
Installing collected packages: cassowary, toga-cassowary, toga-win32, toga, toga-demo
Exception:
Traceback (most recent call last):
  File "c:\users\my_user_name\envs\beeware\lib\shutil.py", line 538, in move
    os.rename(src, real_dst)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'c:\\users\\my_user_name\\envs\\beeware\\Lib\\site-packages\\toga_demo-0.2.2.dist-info\\RECORD.pip' -> 'c:\\users\\my_user_name\\envs\\beeware\\Lib\\site-packages\\toga_demo-0.2.2.dist-info\\RECORD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\pip\commands\install.py", line 317, in run
    prefix=options.prefix_path,
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\pip\req\req_set.py", line 742, in install
    **kwargs
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\pip\req\req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\pip\req\req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\pip\wheel.py", line 528, in move_wheel_files
    shutil.move(temp_record, record)
  File "c:\users\my_user_name\envs\beeware\lib\shutil.py", line 553, in move
    os.unlink(src)
PermissionError: [WinError 5] Zugriff verweigert: 'c:\\users\\my_user_name\\envs\\beeware\\Lib\\site-packages\\toga_demo-0.2.2.dist-info\\RECORD.pip'
```

Error messege says that a file can´t be created because it already exists:

```
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 
```

I guess it's `RECORD.pip`

Cheers
Tset

**Comment by Tset-Noitamotua** [comment]
```
[BEEWARE] λ pip install toga-demo
Requirement already satisfied (use --upgrade to upgrade): toga-demo in c:\users\my_user_name\envs\beeware\lib\site-packages Requirement already satisfied (use --upgrade to upgrade): toga>=0.2.2 in c:\users\my_user_name\envs\beeware\lib\site-packages (from toga-demo)
Requirement already satisfied (use --upgrade to upgrade): toga-win32; sys_platform == "win32" in c:\users\my_user_name\envs\beeware\lib\site-packages (from toga>=0.2.2->toga-demo)
Requirement already satisfied (use --upgrade to upgrade): toga-cassowary in c:\users\my_user_name\envs\beeware\lib\site-packages (from toga-win32; sys_platform == "win32"->toga>=0.2.2->toga-demo)
Requirement already satisfied (use --upgrade to upgrade): cassowary in c:\users\my_user_name\envs\beeware\lib\site-packages (from toga-cassowary->toga-win32; sys_platform == "win32"->toga>=0.2.2->toga-demo)


[BEEWARE] λ toga-demo
Traceback (most recent call last):
  File "c:\python35\Lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\my_user_name\Envs\BEEWARE\Scripts\toga-demo.exe\__main__.py", line 5, in <module>
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\toga_demo\__main__.py", line 6, in <module>
    from .app import TogaDemo
  File "c:\users\my_user_name\envs\beeware\lib\site-packages\toga_demo\app.py", line 4, in <module>
    import toga
ImportError: No module named 'toga'
```

**Comment by freakboy3742** [comment]
As noted on pybee/toga-demo#4, #67, and a couple of others, Window support is lagging behind other platforms at the moment. I'll leave this ticket open as a note for others.

**Comment by bernardsoulier** [comment]
unable to run examples with Toga - toga.contraint module is missing.

I typed in the hello world example and it won't run.  toga-demo also will not run - gives following error:
Traceback (most recent call last):
  File "c:\python\python3.5.1\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python3.5.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\python3.5.1\Scripts\toga-demo.exe\__main__.py", line 5, in <module>
  File "c:\python\python3.5.1\lib\site-packages\toga_demo\__main__.py", line 6, in <module>
    from .app import TogaDemo
  File "c:\python\python3.5.1\lib\site-packages\toga_demo\app.py", line 4, in <module>
    import toga
  File "c:\python\python3.5.1\lib\site-packages\toga\__init__.py", line 91, in <module>
    set_platform()
  File "c:\python\python3.5.1\lib\site-packages\toga\__init__.py", line 73, in set_platform
    locals['platform'] = importlib.import_module(module_name)
  File "c:\python\python3.5.1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\python\python3.5.1\lib\site-packages\toga_win32\__init__.py", line 7, in <module>
    from .widgets.button import *
  File "c:\python\python3.5.1\lib\site-packages\toga_win32\widgets\button.py", line 5, in <module>
    from .base import Widget
  File "c:\python\python3.5.1\lib\site-packages\toga_win32\widgets\base.py", line 3, in <module>
    from toga_cassowary.widget import Widget as CassowaryWidget
  File "c:\python\python3.5.1\lib\site-packages\toga_cassowary\widget.py", line 3, in <module>
    from toga.constraint import Attribute, Constraint
ImportError: No module named 'toga.constraint'

**Comment by JayKayAce** [comment]
I did a `pip` install on the toga library on windows and had some issues regarding the missing Toga part. from what i can see the toga core part is not installed in the site-packages folder. The dist info folder is present but the not the actual source folder with the code inside. 
```
06-01-2017  14:01    <DIR>          .
06-01-2017  14:01    <DIR>          ..
06-01-2017  13:58    <DIR>          cassowary
06-01-2017  13:58    <DIR>          cassowary-0.5.1.dist-info
22-09-2015  21:11               121 README.txt
06-01-2017  13:58    <DIR>          toga-0.2.4.dist-info
06-01-2017  13:58    <DIR>          toga_cassowary
06-01-2017  13:58    <DIR>          toga_cassowary-0.1.2.dist-info
06-01-2017  14:01    <DIR>          toga_demo
06-01-2017  14:01    <DIR>          toga_demo-0.2.4.dist-info
06-01-2017  13:58    <DIR>          toga_win32
06-01-2017  13:58    <DIR>          toga_win32-0.1.2.dist-info
```
And that causes the import error mentioned above.
I would assume there is an error in the toga-core install information, but my skills lack for finding the bug and fixing this.

**Comment by freakboy3742** [comment]
Apologies for all the confusion here. Toga 0.2.0 did a pretty big reorganisation of the installation process, reversing an install dependency. As a result, installing Toga on Windows won't get the expected result. You'll need to manually install each of the components, and uninstall anything that got installed unexpectedly. 

In particular, the Windows backend is still replying on cassowary, but all the toga core code is now referring to colosseum. This reflects a big internal change to the way widgets are laid out. I intend to get Windows support back at some point in the near future, and if you want to help, all assistance is definitely welcome - but in the meantime you definitely need to go in wearing all your helmets and safety pads.

**Comment by voltagex** [comment]
Can this one be closed as well?

**Comment by freakboy3742** [comment]
Yes - the dependency problem has been fixed. toga-demo is still a work in progress, but the base libraries install as expected.
